apiVersion: v1
kind: Service
metadata:
  name: emailservice-svc  # Prefer lowercase and consistent naming
spec:
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice-container
          image: sudharsan0007/thathashop-emailservice:latest
          
