apiVersion: v1
kind: Service
metadata:
  name: loggingservice  # Prefer lowercase and consistent naming
spec:
  selector:
    app: loggingservice
  ports:
    - protocol: TCP
      port: 3502
      targetPort: 3502

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggingservice-deployment
  labels:
    app: loggingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggingservice
  template:
    metadata:
      labels:
        app: loggingservice
    spec:
      containers:
        - name: loggingservice-container
          image: sudharsan0007/thathashop-loggingservice:latest
          
