apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: loggingservice
  name: loggingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loggingservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: loggingservice
    spec:
      containers:
        - image: loggingservice
          name: thathashop-loggingservice
      restartPolicy: Always
