apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: orderservice
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: orderservice
    spec:
      containers:
        - image: orderservice
          name: thathashop-orderservice
          ports:
            - containerPort: 5004
              protocol: TCP
      restartPolicy: Always
