apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: vault
    spec:
      containers:
        - args:
            - vault
            - server
            - -dev
          env:
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: 0.0.0.0:8200
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: myroot
          image: hashicorp/vault:1.15.0
          name: vault
          ports:
            - containerPort: 8200
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      restartPolicy: Always
